<?php

require('../vendor/autoload.php');
require('../framework/config.php');
define('ROOT', dirname(dirname(__FILE__)));

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Schema\Blueprint;

  try {
    $dbName = $config['db']['database'];
    $sql = "CREATE DATABASE IF NOT EXISTS `$dbName` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin;";
    $dbConfig = array_merge([], $config['db']);
    unset($dbConfig['database']);
    $capsule = new Capsule;
    $capsule->addConnection($dbConfig);
    $capsule->setAsGlobal();
    $capsule->bootEloquent();
    Capsule::statement($sql);
  } catch (Exception $e) {
    echo $e;
    die('FAIL');
  }


  $files = scandir('.');
  $files = array_diff($files, array('.', '..', 'migrations', __FILE__));
  foreach ($files as $file) {
    try {
      require_once($file);
    } catch (Exception $e) {
      echo $e;
    }
  }

  $capsule = new Capsule;
  $capsule->addConnection($config['db']);
  $capsule->setAsGlobal();
  $capsule->bootEloquent();
  Capsule::statement($sql);


  $arrOptions = [
    [1, -2, 'Option 1', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [2, -2, 'Option 2', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [3, -2, 'Option 3', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [4, -2, 'Option 4', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [5, -2, 'Option 5', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [6, -2, 'Option 6', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
  ];

  foreach ($arrOptions as $option) {
      Capsule::insert('INSERT INTO ' . Capsule::getTablePrefix()
        . 'attribute (id, parent_id, name, created_at, updated_at)'
        . 'VALUES (?, ?, ?, ?, ?)',
        $option
      );
    }

  $arrAttribute = [
    [7, -1, 'Attribute 1', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [8, -1, 'Attribute 2', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [9, -1, 'Attribute 3', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [10, -1, 'Attribute 4', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [11, -1, 'Attribute 5', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [12, -1, 'Attribute 6', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
  ];

  foreach ($arrAttribute as $option) {
      Capsule::insert('INSERT INTO ' . Capsule::getTablePrefix()
        . 'attribute (id, parent_id, name, created_at, updated_at)'
        . 'VALUES (?, ?, ?, ?, ?)',
        $option
      );
  }

  $arrRole = [
    [1,'Quản trị viên cấp cao', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [2,'Quản trị viên nội dung', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [3,'Quản trị viên đơn hàng', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [4,'Quản trị viên bài viết', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')],
    [5,'Quản trị viên sản phẩm', date('Y-m-d H:i:s'), date('Y-m-d H:i:s')]
  ];

  $arrPermission = [
    ['1','order','GET','/order',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order/search',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order?order_status=new',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order?order_status=confirm',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order?order_status=confirm&payment_status=0',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order?order_status=done',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order?order_status=return',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','GET','/order?order_status=cancel',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','order','PUT','/order/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','GET','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','GET','/product/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','GET','/product/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','POST','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','PUT','/product/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','DELETE','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product','POST','/product/duplicate/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','import_product','GET','/import_product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','import_product','GET','/import_product/template',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','import_product','POST','/import_product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','collection','GET','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','collection','GET','/collection/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','collection','GET','/collection/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','collection','POST','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','collection','PUT','/collection/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','collection','DELETE','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','GET','/product_buy_together',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','GET','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','GET','/product_buy_together/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','POST','/product_buy_together',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','PUT','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','POST','/product_buy_together/one',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','product_buy_together','DELETE','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','attribute','GET','/attribute',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','attribute','GET','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','attribute','GET','/attribute/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','attribute','POST','/attribute',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','attribute','PUT','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','attribute','DELETE','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','coupon','GET','/coupon',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','coupon','GET','/coupon/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','coupon','GET','/coupon/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','coupon','POST','/coupon',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','coupon','PUT','/coupon/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','coupon','DELETE','/coupon',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','sale','GET','/sale',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','sale','GET','/sale/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','sale','GET','/sale/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','sale','POST','/sale',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','sale','PUT','/sale/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','sale','DELETE','/sale',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','customer','GET','/customer',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','customer','GET','/customer/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','customer','PUT','/customer/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','customer','GET','/customer/order/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','customer','GET','/customer/export',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','customer','DELETE','/customer',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','GET','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','GET','/article/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','GET','/article/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','POST','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','PUT','/article/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','DELETE','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','article','POST','/article/duplicate/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','blog','GET','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','blog','GET','/blog/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','blog','GET','/blog/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','blog','POST','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','blog','PUT','/blog/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','blog','DELETE','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','page','GET','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','page','GET','/page/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','page','GET','/page/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','page','POST','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','page','PUT','/page/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','page','DELETE','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','gallery','GET','/gallery',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','gallery','GET','/gallery/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','gallery','GET','/gallery/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','gallery','POST','/gallery',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','gallery','PUT','/gallery/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','gallery','DELETE','/gallery',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','photo','GET','/photo/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','photo','GET','/photo/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','photo','POST','/photo',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','photo','PUT','/photo/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','photo','DELETE','/photo/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','review','GET','/review',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','subscriber','GET','/subscriber',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','comment','GET','/comment',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','comment','GET','/comment/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','comment','GET','/comment/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','comment','PUT','/comment/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','comment','DELETE','/comment',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','contact','GET','/contact',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','contact','GET','/contact/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','contact','GET','/contact?read=1',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','contact','GET','/contact?reply=1',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','contact','PUT','/contact/updateStatus',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','contact','DELETE','/contact/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','GET','/menu',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','GET','/menu/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','GET','/menu/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','PUT','/menu/updatePriority',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','POST','/menu',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','PUT','/menu/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','DELETE','/menu/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','menu','DELETE','/menu',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','setting','GET','/setting',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','setting','PUT','/setting',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','library','GET','/library',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','testimonial','GET','/testimonial',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','testimonial','GET','/testimonial/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','testimonial','GET','/testimonial/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','testimonial','POST','/testimonial',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','testimonial','PUT','/testimonial/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','testimonial','DELETE','/testimonial',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','client','GET','/client',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','client','GET','/client/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','client','GET','/client/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','client','POST','/client',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','client','PUT','/client/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','client','DELETE','/client',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','shipping_fee','GET','/shipping_fee',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','shipping_fee','GET','/shipping_fee/edit/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','shipping_fee','GET','/shipping_fee/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','shipping_fee','POST','/shipping_fee',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','shipping_fee','PUT','/shipping_fee/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','shipping_fee','DELETE','/shipping_fee/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','GET','/user',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','GET','/user/history',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','GET','/user/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','GET','/user/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','PUT','/user/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','POST','/user',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','DELETE','/user/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','GET','/user/email/order',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['1','user','GET','/user/email/contact',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','GET','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','GET','/product/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','GET','/product/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','POST','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','PUT','/product/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','DELETE','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product','POST','/product/duplicate/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','collection','GET','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','collection','GET','/collection/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','collection','GET','/collection/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','collection','POST','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','collection','PUT','/collection/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','collection','DELETE','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','GET','/product_buy_together',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','GET','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','GET','/product_buy_together/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','POST','/product_buy_together',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','PUT','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','POST','/product_buy_together/one',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','product_buy_together','DELETE','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','attribute','GET','/attribute',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','attribute','GET','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','attribute','GET','/attribute/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','attribute','POST','/attribute',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','attribute','PUT','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','attribute','DELETE','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','coupon','GET','/coupon',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','coupon','GET','/coupon/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','coupon','GET','/coupon/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','coupon','POST','/coupon',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','coupon','PUT','/coupon/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','coupon','DELETE','/coupon',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','sale','GET','/sale',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','sale','GET','/sale/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','sale','GET','/sale/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','sale','POST','/sale',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','sale','PUT','/sale/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','sale','DELETE','/sale',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','customer','GET','/customer',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','customer','GET','/customer/order/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','customer','DELETE','/customer',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','GET','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','GET','/article/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','GET','/article/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','POST','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','PUT','/article/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','DELETE','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','article','POST','/article/duplicate/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','blog','GET','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','blog','GET','/blog/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','blog','GET','/blog/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','blog','POST','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','blog','PUT','/blog/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','blog','DELETE','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','page','GET','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','page','GET','/page/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','page','GET','/page/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','page','POST','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','page','PUT','/page/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','page','DELETE','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','gallery','GET','/gallery',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','gallery','GET','/gallery/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','gallery','GET','/gallery/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','gallery','POST','/gallery',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','gallery','PUT','/gallery/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','gallery','DELETE','/gallery',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','photo','GET','/photo/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','photo','GET','/photo/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','photo','POST','/photo',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','photo','PUT','/photo/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','photo','DELETE','/photo/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','review','GET','/review',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','subscriber','GET','/subscriber',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','comment','GET','/comment',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','comment','GET','/comment/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','comment','GET','/comment/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','comment','PUT','/comment/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','comment','DELETE','/comment',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','GET','/menu',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','GET','/menu/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','GET','/menu/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','PUT','/menu/updatePriority',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','POST','/menu',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','PUT','/menu/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','DELETE','/menu/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','menu','DELETE','/menu',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','setting','GET','/setting',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','setting','PUT','/setting',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','library','GET','/library',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','testimonial','GET','/testimonial',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','testimonial','GET','/testimonial/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','testimonial','GET','/testimonial/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','testimonial','POST','/testimonial',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','testimonial','PUT','/testimonial/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','testimonial','DELETE','/testimonial',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','client','GET','/client',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','client','GET','/client/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','client','GET','/client/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','client','POST','/client',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','client','PUT','/client/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','client','DELETE','/client',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','shipping_fee','GET','/shipping_fee',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','shipping_fee','GET','/shipping_fee/edit/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','shipping_fee','GET','/shipping_fee/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','shipping_fee','POST','/shipping_fee',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','shipping_fee','PUT','/shipping_fee/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['2','shipping_fee','DELETE','/shipping_fee/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order/search',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order?order_status=new',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order?order_status=confirm',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order?order_status=confirm&payment_status=0',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order?order_status=done',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order?order_status=return',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','GET','/order?order_status=cancel',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','order','PUT','/order/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','contact','GET','/contact',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','contact','GET','/contact/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','contact','GET','/contact?read=1',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','contact','GET','/contact?reply=1',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','contact','PUT','/contact/updateStatus',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','contact','DELETE','/contact/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','user','GET','/user/email/order',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['3','user','GET','/user/email/contact',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','GET','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','GET','/article/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','GET','/article/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','POST','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','PUT','/article/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','DELETE','/article',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','article','POST','/article/duplicate/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','blog','GET','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','blog','GET','/blog/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','blog','GET','/blog/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','blog','POST','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','blog','PUT','/blog/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','blog','DELETE','/blog',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','page','GET','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','page','GET','/page/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','page','GET','/page/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','page','POST','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','page','PUT','/page/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['4','page','DELETE','/page',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','GET','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','GET','/product/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','GET','/product/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','POST','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','PUT','/product/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','DELETE','/product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product','POST','/product/duplicate/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','import_product','GET','/import_product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','import_product','GET','/import_product/template',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','import_product','POST','/import_product',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','collection','GET','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','collection','GET','/collection/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','collection','GET','/collection/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','collection','POST','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','collection','PUT','/collection/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','collection','DELETE','/collection',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','GET','/product_buy_together',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','GET','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','GET','/product_buy_together/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','POST','/product_buy_together',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','PUT','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','POST','/product_buy_together/one',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','product_buy_together','DELETE','/product_buy_together/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','attribute','GET','/attribute',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','attribute','GET','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','attribute','GET','/attribute/create',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','attribute','POST','/attribute',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','attribute','PUT','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')],
    ['5','attribute','DELETE','/attribute/{id}',date('Y-m-d H:i:s'),date('Y-m-d H:i:s')]
  ];

  $arrRegion = [
    [123,'Hà Nội',1],
    [124,'Hà Giang',1],
    [125,'Cao Bằng',1],
    [126,'Bắc Kạn',1],
    [127,'Tuyên Quang',1],
    [128,'Lào Cai',1],
    [129,'Điện Biên',1],
    [130,'Lai Châu',1],
    [131,'Sơn La',1],
    [132,'Yên Bái',1],
    [133,'Hoà Bình',1],
    [134,'Thái Nguyên',1],
    [135,'Lạng Sơn',1],
    [136,'Quảng Ninh',1],
    [137,'Bắc Giang',1],
    [138,'Phú Thọ',1],
    [139,'Vĩnh Phúc',1],
    [140,'Bắc Ninh',1],
    [141,'Hải Dương',1],
    [142,'Hải Phòng',1],
    [143,'Hưng Yên',1],
    [144,'Thái Bình',1],
    [145,'Hà Nam',1],
    [146,'Nam Định',1],
    [147,'Ninh Bình',1],
    [148,'Thanh Hóa',2],
    [149,'Nghệ An',2],
    [150,'Hà Tĩnh',2],
    [151,'Quảng Bình',2],
    [152,'Quảng Trị',2],
    [153,'Thừa Thiên Huế',2],
    [154,'Đà Nẵng',2],
    [155,'Quảng Nam',2],
    [156,'Quảng Ngãi',2],
    [157,'Bình Định',2],
    [158,'Phú Yên',2],
    [159,'Khánh Hoà',2],
    [160,'Ninh Thuận',2],
    [161,'Bình Thuận',2],
    [162,'Kon Tum',2],
    [163,'Gia Lai',2],
    [164,'Đăk Lăk',2],
    [165,'Đăk Nông',2],
    [166,'Lâm Đồng',2],
    [167,'Bình Phước',3],
    [168,'Tây Ninh',3],
    [169,'Bình Dương',3],
    [170,'Đồng Nai',3],
    [171,'Bà Rịa - Vũng Tàu',3],
    [172,'Hồ Chí Minh',3],
    [173,'Long An',3],
    [174,'Tiền Giang',3],
    [175,'Bến Tre',3],
    [176,'Trà Vinh',3],
    [177,'Vĩnh Long',3],
    [178,'Đồng Tháp',3],
    [179,'An Giang',3],
    [180,'Kiên Giang',3],
    [181,'Cần Thơ',3],
    [182,'Hậu Giang',3],
    [183,'Sóc Trăng',3],
    [184,'Bạc Liêu',3],
    [185,'Cà Mau',3]
  ];

  $arrSubRegion = [
    [1,'Quận Hoàn Kiếm','123'],
    [2,'Quận Tây Hồ','123'],
    [3,'Quận Long Biên','123'],
    [4,'Quận Cầu Giấy','123'],
    [5,'Quận Đống Đa','123'],
    [6,'Quận Hai Bà Trưng','123'],
    [7,'Quận Hoàng Mai','123'],
    [8,'Quận Thanh Xuân','123'],
    [9,'Huyện Sóc Sơn','123'],
    [10,'Huyện Đông Anh','123'],
    [11,'Huyện Gia Lâm','123'],
    [12,'Quận Nam Từ Liêm','123'],
    [13,'Huyện Thanh Trì','123'],
    [14,'Thị xã Hà Giang','124'],
    [15,'Huyện Đồng Văn','124'],
    [16,'Huyện Mèo Vạc','124'],
    [17,'Huyện Yên Minh','124'],
    [18,'Huyện Quản Bạ','124'],
    [19,'Huyện Vị Xuyên','124'],
    [20,'Huyện Bắc Mê','124'],
    [21,'Huyện Hoàng Su Phì','124'],
    [22,'Huyện Xín Mần','124'],
    [23,'Huyện Bắc Quang','124'],
    [24,'Huyện Quang Bình','124'],
    [25,'Thành phố Cao Bằng','125'],
    [26,'Huyện Bảo Lâm','125'],
    [27,'Huyện Bảo Lạc','125'],
    [28,'Huyện Thông Nông','125'],
    [29,'Huyện Hà Quảng','125'],
    [30,'Huyện Trà Lĩnh','125'],
    [31,'Huyện Trùng Khánh','125'],
    [32,'Huyện Hạ Lang','125'],
    [33,'Huyện Quảng Uyên','125'],
    [34,'Huyện Phục Hoà','125'],
    [35,'Huyện Hoà An','125'],
    [36,'Huyện Nguyên Bình','125'],
    [37,'Huyện Thạch An','125'],
    [38,'Thành phố Bắc Kạn','126'],
    [39,'Huyện Pác Nặm','126'],
    [40,'Huyện Ba Bể','126'],
    [41,'Huyện Ngân Sơn','126'],
    [42,'Huyện Bạch Thông','126'],
    [43,'Huyện Chợ Đồn','126'],
    [44,'Huyện Chợ Mới','126'],
    [45,'Huyện Na Rì','126'],
    [46,'Thành phố Tuyên Quang','127'],
    [47,'Huyện Na Hang','127'],
    [48,'Huyện Chiêm Hóa','127'],
    [49,'Huyện Hàm Yên','127'],
    [50,'Huyện Yên Sơn','127'],
    [51,'Huyện Sơn Dương','127'],
    [52,'Thành phố Lào Cai','128'],
    [53,'Huyện Bát Xát','128'],
    [54,'Huyện Mường Khương','128'],
    [55,'Huyện Si Ma Cai','128'],
    [56,'Huyện Bắc Hà','128'],
    [57,'Huyện Bảo Thắng','128'],
    [58,'Huyện Bảo Yên','128'],
    [59,'Huyện Sa Pa','128'],
    [60,'Huyện Văn Bàn','128'],
    [61,'Thành phố Điện Biên Phủ','129'],
    [62,'Thị xã Mường Lay','129'],
    [63,'Huyện Mường Nhé','129'],
    [64,'Huyện Mường Chà','129'],
    [65,'Huyện Tủa Chùa','129'],
    [66,'Huyện Tuần Giáo','129'],
    [67,'Huyện Điện Biên','129'],
    [68,'Huyện Điện Biên Đông','129'],
    [69,'Huyện Tam Đường','130'],
    [70,'Huyện Mường Tè','130'],
    [71,'Huyện Sìn Hồ','130'],
    [72,'Huyện Phong Thổ','130'],
    [73,'Huyện Than Uyên','130'],
    [74,'Thị xã Lai châu','130'],
    [75,'Thành phố Sơn La','131'],
    [76,'Huyện Quỳnh Nhai','131'],
    [77,'Huyện Thuận Châu','131'],
    [78,'Huyện Mường La','131'],
    [79,'Huyện Bắc Yên','131'],
    [80,'Huyện Phù Yên','131'],
    [81,'Huyện Mộc Châu','131'],
    [82,'Huyện Yên Châu','131'],
    [83,'Huyện Mai Sơn','131'],
    [84,'Huyện Sông Mã','131'],
    [85,'Huyện Sốp Cộp','131'],
    [86,'Thành phố Yên Bái','132'],
    [87,'Thị xã Nghĩa Lộ','132'],
    [88,'Huyện Lục Yên','132'],
    [89,'Huyện Văn Yên','132'],
    [90,'Huyện Mù Căng Chải','132'],
    [91,'Huyện Trấn Yên','132'],
    [92,'Huyện Trạm Tấu','132'],
    [93,'Huyện Văn Chấn','132'],
    [94,'Huyện Yên Bình','132'],
    [95,'Thị xã Hòa Bình','133'],
    [96,'Huyện Đà Bắc','133'],
    [97,'Huyện Kỳ Sơn','133'],
    [98,'Huyện Lương Sơn','133'],
    [99,'Huyện Kim Bôi','133'],
    [100,'Huyện Cao Phong','133'],
    [101,'Huyện Tân Lạc','133'],
    [102,'Huyện Mai Châu','133'],
    [103,'Huyện Lạc Sơn','133'],
    [104,'Huyện Yên Thủy','133'],
    [105,'Huyện Lạc Thủy','133'],
    [106,'Thành phố Thái Nguyên','134'],
    [107,'Thành phố Sông Công','134'],
    [108,'Huyện Định Hóa','134'],
    [109,'Huyện Phú Lương','134'],
    [110,'Huyện Đồng Hỷ','134'],
    [111,'Huyện Võ Nhai','134'],
    [112,'Huyện Đại Từ','134'],
    [113,'Thị xã Phổ Yên','134'],
    [114,'Huyện Phú Bình','134'],
    [115,'Thành phố Lạng Sơn','135'],
    [116,'Huyện Tràng Định','135'],
    [117,'Huyện Bình Gia','135'],
    [118,'Huyện Văn Lãng','135'],
    [119,'Huyện Cao Lộc','135'],
    [120,'Huyện Văn Quan','135'],
    [121,'Huyện Bắc Sơn','135'],
    [122,'Huyện Hữu Lũng','135'],
    [123,'Huyện Chi Lăng','135'],
    [124,'Huyện Lộc Bình','135'],
    [125,'Huyện Đình Lập','135'],
    [126,'Thành phố Hạ Long','136'],
    [127,'Thành phố Móng Cái','136'],
    [128,'Thành phố Cẩm Phả','136'],
    [129,'Thành phố Uông Bí','136'],
    [130,'Huyện Bình Liêu','136'],
    [131,'Huyện Tiên Yên','136'],
    [132,'Huyện Đầm Hà','136'],
    [133,'Huyện Hải Hà','136'],
    [134,'Huyện Ba Chẽ','136'],
    [135,'Huyện Vân Đồn','136'],
    [136,'Huyện Hoành Bồ','136'],
    [137,'Thị xã Đông Triều','136'],
    [138,'Thị xã Quảng Yên','136'],
    [139,'Huyện Cô Tô','136'],
    [140,'Thành phố Bắc Giang','137'],
    [141,'Huyện Yên Thế','137'],
    [142,'Huyện Tân Yên','137'],
    [143,'Huyện Lạng Giang','137'],
    [144,'Huyện Lục Nam','137'],
    [145,'Huyện Lục Ngạn','137'],
    [146,'Huyện Sơn Động','137'],
    [147,'Huyện Yên Dũng','137'],
    [148,'Huyện Việt Yên','137'],
    [149,'Huyện Hiệp Hòa','137'],
    [150,'Thành phố Việt Trì','138'],
    [151,'Thị xã Phú Thọ','138'],
    [152,'Huyện Đoan Hùng','138'],
    [153,'Huyện Hạ Hoà','138'],
    [154,'Huyện Thanh Ba','138'],
    [155,'Huyện Phù Ninh','138'],
    [156,'Huyện Yên Lập','138'],
    [157,'Huyện Cẩm Khê','138'],
    [158,'Huyện Tam Nông','138'],
    [159,'Huyện Lâm Thao','138'],
    [160,'Huyện Thanh Sơn','138'],
    [161,'Huyện Thanh Thuỷ','138'],
    [162,'Thành phố Vĩnh Yên','139'],
    [163,'Thị xã Phúc Yên','139'],
    [164,'Huyện Lập Thạch','139'],
    [165,'Huyện Tam Dương','139'],
    [166,'Huyện Tam Đảo','139'],
    [167,'Huyện Bình Xuyên','139'],
    [168,'Huyện Mê Linh','123'],
    [169,'Huyện Yên Lạc','139'],
    [170,'Huyện Vĩnh Tường','139'],
    [171,'Thành phố Bắc Ninh','140'],
    [172,'Huyện Yên Phong','140'],
    [173,'Huyện Quế Võ','140'],
    [174,'Huyện Tiên Du','140'],
    [175,'Thị xã Từ Sơn','140'],
    [176,'Huyện Thuận Thành','140'],
    [177,'Huyện Gia Bình','140'],
    [178,'Huyện Lương Tài','140'],
    [179,'Quận Hà Đông','123'],
    [180,'Thị xã Sơn Tây','123'],
    [181,'Huyện Ba Vì','123'],
    [182,'Huyện Phúc Thọ','123'],
    [183,'Huyện Đan Phượng','123'],
    [184,'Huyện Hoài Đức','123'],
    [185,'Huyện Quốc Oai','123'],
    [186,'Huyện Thạch Thất','123'],
    [187,'Huyện Chương Mỹ','123'],
    [188,'Huyện Thanh Oai','123'],
    [189,'Huyện Thường Tín','123'],
    [190,'Huyện Phú Xuyên','123'],
    [191,'Huyện ứng Hòa','123'],
    [192,'Huyện Mỹ Đức','123'],
    [193,'Thành phố Hải Dương','141'],
    [194,'Thị xã Chí Linh','141'],
    [195,'Huyện Nam Sách','141'],
    [196,'Huyện Kinh Môn','141'],
    [197,'Huyện Kim Thành','141'],
    [198,'Huyện Thanh Hà','141'],
    [199,'Huyện Cẩm Giàng','141'],
    [200,'Huyện Bình Giang','141'],
    [201,'Huyện Gia Lộc','141'],
    [202,'Huyện Tứ Kỳ','141'],
    [203,'Huyện Ninh Giang','141'],
    [204,'Huyện Thanh Miện','141'],
    [205,'Quận Hồng Bàng','142'],
    [206,'Quận Ngô Quyền','142'],
    [207,'Quận Lê Chân','142'],
    [208,'Quận Hải An','142'],
    [209,'Quận Kiến An','142'],
    [210,'Quận Đồ Sơn','142'],
    [211,'Huyện Thuỷ Nguyên','142'],
    [212,'Huyện An Dương','142'],
    [213,'Huyện An Lão','142'],
    [214,'Huyện Kiến Thuỵ','142'],
    [215,'Huyện Tiên Lãng','142'],
    [216,'Huyện Vĩnh Bảo','142'],
    [217,'Huyện Cát Hải','142'],
    [218,'Huyện Bạch Long Vĩ','142'],
    [219,'Thành phố Hưng Yên','143'],
    [220,'Huyện Văn Lâm','143'],
    [221,'Huyện Văn Giang','143'],
    [222,'Huyện Yên Mỹ','143'],
    [223,'Huyện Mỹ Hào','143'],
    [224,'Huyện Ân Thi','143'],
    [225,'Huyện Khoái Châu','143'],
    [226,'Huyện Kim Động','143'],
    [227,'Huyện Tiên Lữ','143'],
    [228,'Huyện Phù Cừ','143'],
    [229,'Thành phố Thái Bình','144'],
    [230,'Huyện Quỳnh Phụ','144'],
    [231,'Huyện Hưng Hà','144'],
    [232,'Huyện Đông Hưng','144'],
    [233,'Huyện Thái Thụy','144'],
    [234,'Huyện Tiền Hải','144'],
    [235,'Huyện Kiến Xương','144'],
    [236,'Huyện Vũ Thư','144'],
    [237,'Thành phố Phủ Lý','145'],
    [238,'Huyện Duy Tiên','145'],
    [239,'Huyện Kim Bảng','145'],
    [240,'Huyện Thanh Liêm','145'],
    [241,'Huyện Bình Lục','145'],
    [242,'Huyện Lý Nhân','145'],
    [243,'Thành phố Nam Định','146'],
    [244,'Huyện Mỹ Lộc','146'],
    [245,'Huyện Vụ Bản','146'],
    [246,'Huyện ý Yên','146'],
    [247,'Huyện Nghĩa Hưng','146'],
    [248,'Huyện Nam Trực','146'],
    [249,'Huyện Trực Ninh','146'],
    [250,'Huyện Xuân Trường','146'],
    [251,'Huyện Giao Thủy','146'],
    [252,'Huyện Hải Hậu','146'],
    [253,'Thành phố Ninh Bình','147'],
    [254,'Thành phố Tam Điệp','147'],
    [255,'Huyện Nho Quan','147'],
    [256,'Huyện Gia Viễn','147'],
    [257,'Huyện Hoa Lư','147'],
    [258,'Huyện Yên Khánh','147'],
    [259,'Huyện Kim Sơn','147'],
    [260,'Huyện Yên Mô','147'],
    [261,'Thành phố Thanh Hóa','148'],
    [262,'Thị xã Bỉm Sơn','148'],
    [263,'Thị xã Sầm Sơn','148'],
    [264,'Huyện Mường Lát','148'],
    [265,'Huyện Quan Hóa','148'],
    [266,'Huyện Bá Thước','148'],
    [267,'Huyện Quan Sơn','148'],
    [268,'Huyện Lang Chánh','148'],
    [269,'Huyện Ngọc Lặc','148'],
    [270,'Huyện Cẩm Thủy','148'],
    [271,'Huyện Thạch Thành','148'],
    [272,'Huyện Hà Trung','148'],
    [273,'Huyện Vĩnh Lộc','148'],
    [274,'Huyện Yên Định','148'],
    [275,'Huyện Thọ Xuân','148'],
    [276,'Huyện Thường Xuân','148'],
    [277,'Huyện Triệu Sơn','148'],
    [278,'Huyện Thiệu Hoá','148'],
    [279,'Huyện Hoằng Hóa','148'],
    [280,'Huyện Hậu Lộc','148'],
    [281,'Huyện Nga Sơn','148'],
    [282,'Huyện Như Xuân','148'],
    [283,'Huyện Như Thanh','148'],
    [284,'Huyện Nông Cống','148'],
    [285,'Huyện Đông Sơn','148'],
    [286,'Huyện Quảng Xương','148'],
    [287,'Huyện Tĩnh Gia','148'],
    [288,'Thành phố Vinh','149'],
    [289,'Thị xã Cửa Lò','149'],
    [290,'Huyện Quế Phong','149'],
    [291,'Huyện Quỳ Châu','149'],
    [292,'Huyện Tương Dương','149'],
    [293,'Huyện Nghĩa Đàn','149'],
    [294,'Huyện Quỳ Hợp','149'],
    [295,'Huyện Quỳnh Lưu','149'],
    [296,'Huyện Con Cuông','149'],
    [297,'Huyện Tân Kỳ','149'],
    [298,'Huyện Anh Sơn','149'],
    [299,'Huyện Diễn Châu','149'],
    [300,'Huyện Yên Thành','149'],
    [301,'Huyện Đô Lương','149'],
    [302,'Huyện Thanh Chương','149'],
    [303,'Huyện Nghi Lộc','149'],
    [304,'Huyện Nam Đàn','149'],
    [305,'Huyện Hưng Nguyên','149'],
    [306,'Thành phố Hà Tĩnh','150'],
    [307,'Thị xã Hồng Lĩnh','150'],
    [308,'Huyện Hương Sơn','150'],
    [309,'Huyện Đức Thọ','150'],
    [310,'Huyện Vũ Quang','150'],
    [311,'Huyện Nghi Xuân','150'],
    [312,'Huyện Can Lộc','150'],
    [313,'Huyện Hương Khê','150'],
    [314,'Huyện Thạch Hà','150'],
    [315,'Huyện Cẩm Xuyên','150'],
    [316,'Huyện Kỳ Anh','150'],
    [317,'Thành phố Đồng Hới','151'],
    [318,'Huyện Minh Hóa','151'],
    [319,'Huyện Tuyên Hóa','151'],
    [320,'Huyện Quảng Trạch','151'],
    [321,'Huyện Bố Trạch','151'],
    [322,'Huyện Quảng Ninh','151'],
    [323,'Huyện Lệ Thủy','151'],
    [324,'Thị xã Đông Hà','152'],
    [325,'Thị xã Quảng Trị','152'],
    [326,'Huyện Vĩnh Linh','152'],
    [327,'Huyện Hướng Hóa','152'],
    [328,'Huyện Gio Linh','152'],
    [329,'Huyện Đa Krông','152'],
    [330,'Huyện Cam Lộ','152'],
    [331,'Huyện Triệu Phong','152'],
    [332,'Huyện Hải Lăng','152'],
    [333,'Huyện Đảo Cồn Cỏ','152'],
    [334,'Thành phố Huế','153'],
    [335,'Huyện Phong Điền','153'],
    [336,'Huyện Quảng Điền','153'],
    [337,'Huyện Phú Vang','153'],
    [338,'Thị xã Hương Thủy','153'],
    [339,'Huyện Hương Trà','153'],
    [340,'Huyện A Lưới','153'],
    [341,'Huyện Phú Lộc','153'],
    [342,'Huyện Nam Đông','153'],
    [343,'Quận Liên Chiểu','154'],
    [344,'Quận Thanh Khê','154'],
    [345,'Quận Hải Châu','154'],
    [346,'Quận Sơn Trà','154'],
    [347,'Quận Ngũ Hành Sơn','154'],
    [348,'Huyện Hoà Vang','154'],
    [349,'Huyện Hoàng Sa','154'],
    [350,'Quận Cẩm Lệ','154'],
    [351,'Thành phố Tam Kỳ','155'],
    [352,'Thành phố Hội An','155'],
    [353,'Huyện Tây Giang','155'],
    [354,'Huyện Đông Giang','155'],
    [355,'Huyện Đại Lộc','155'],
    [356,'Thị xã Điện Bàn','155'],
    [357,'Huyện Duy Xuyên','155'],
    [358,'Huyện Quế Sơn','155'],
    [359,'Huyện Nam Giang','155'],
    [360,'Huyện Phước Sơn','155'],
    [361,'Huyện Hiệp Đức','155'],
    [362,'Huyện Thăng Bình','155'],
    [363,'Huyện Tiên Phước','155'],
    [364,'Huyện Bắc Trà My','155'],
    [365,'Huyện Nam Trà My','155'],
    [366,'Huyện Núi Thành','155'],
    [367,'Huyện Phú Ninh','155'],
    [368,'Thành phố Quảng Ngãi','156'],
    [369,'Huyện Bình Sơn','156'],
    [370,'Huyện Trà Bồng','156'],
    [371,'Huyên Tây Trà','156'],
    [372,'Huyện Sơn Tịnh','156'],
    [373,'Huyện Tư Nghĩa','156'],
    [374,'Huyện Sơn Hà','156'],
    [375,'Huyện Sơn Tây','156'],
    [376,'Huyện Minh Long','156'],
    [377,'Huyện Nghĩa Hành','156'],
    [378,'Huyện Mộ Đức','156'],
    [379,'Huyện Đức Phổ','156'],
    [380,'Huyện Ba Tơ','156'],
    [381,'Huyện Lý Sơn','156'],
    [382,'Thành phố Qui Nhơn','157'],
    [383,'Huyện Hoài Nhơn','157'],
    [384,'Huyện Hoài Ân','157'],
    [385,'Huyện Phù Mỹ','157'],
    [386,'Huyện Vĩnh Thạnh','157'],
    [387,'Huyện Tây Sơn','157'],
    [388,'Huyện Phù Cát','157'],
    [389,'Huyện An Nhơn','157'],
    [390,'Huyện Tuy Phước','157'],
    [391,'Huyện Vân Canh','157'],
    [392,'Thành Phố Tuy Hòa','158'],
    [393,'Thị xã Sông Cầu','158'],
    [394,'Huyện Đồng Xuân','158'],
    [395,'Huyện Tuy An','158'],
    [396,'Huyện Sơn Hòa','158'],
    [397,'Huyện Sông Hinh','158'],
    [398,'Huyện Tuy Hòa','158'],
    [399,'Huyện Phú Hoà','158'],
    [400,'Huyện Tây Hoà','158'],
    [401,'Huyện Đông Hoà','158'],
    [402,'Thành phố Nha Trang','159'],
    [403,'Thành phố Cam Ranh','159'],
    [404,'Huyện Vạn Ninh','159'],
    [405,'Thị xã Ninh Hòa','159'],
    [406,'Huyện Khánh Vĩnh','159'],
    [407,'Huyện Diên Khánh','159'],
    [408,'Huyện Khánh Sơn','159'],
    [409,'Huyện Trường Sa','159'],
    [410,'Thị xã Phan Rang-Tháp Chàm','160'],
    [411,'Huyện Bác ái','160'],
    [412,'Huyện Ninh Sơn','160'],
    [413,'Huyện Ninh Hải','160'],
    [414,'Huyện Ninh Phước','160'],
    [415,'Huyện Thuận Bắc','160'],
    [416,'Thành phố Phan Thiết','161'],
    [417,'Huyện Tuy Phong','161'],
    [418,'Huyện Bắc Bình','161'],
    [419,'Huyện Hàm Thuận Bắc','161'],
    [420,'Huyện Hàm Thuận Nam','161'],
    [421,'Huyện Tánh Linh','161'],
    [422,'Huyện Đức Linh','161'],
    [423,'Huyện Hàm Tân','161'],
    [424,'Huyện Phú Quí','161'],
    [425,'Thị xã La Gi','161'],
    [426,'Thành phố Kon Tum','162'],
    [427,'Huyện Đắk Glei','162'],
    [428,'Huyện Ngọc Hồi','162'],
    [429,'Huyện Đắk Tô','162'],
    [430,'Huyện Kon Plông','162'],
    [431,'Huyện Kon Rẫy','162'],
    [432,'Huyện Đắk Hà','162'],
    [433,'Huyện Sa Thầy','162'],
    [434,'Huyện Tu Mơ Rông','162'],
    [435,'Thành phố Pleiku','163'],
    [436,'Thị Xã An Khê','163'],
    [437,'Huyện KBang','163'],
    [438,'Huyện Đăk Đoa','163'],
    [439,'Huyện Chư Păh','163'],
    [440,'Huyện Ia Grai','163'],
    [441,'Huyện Mang Yang','163'],
    [442,'Huyện Kông Chro','163'],
    [443,'Huyện Đức Cơ','163'],
    [444,'Huyện Chư Prông','163'],
    [445,'Huyện Chư Sê','163'],
    [446,'Huyện Đăk Pơ','163'],
    [447,'Huyện Ia Pa','163'],
    [448,'Thị xã Ayun Pa','163'],
    [449,'Huyện Krông Pa','163'],
    [450,'Thành phố Buôn Ma Thuột','164'],
    [451,'Huyện Ea H\'leo','164'],
    [452,'Huyện Ea Súp','164'],
    [453,'Huyện Buôn Đôn','164'],
    [454,'Huyện Cư M\'gar','164'],
    [455,'Huyện Krông Búk','164'],
    [456,'Huyện Krông Năng','164'],
    [457,'Huyện Ea Kar','164'],
    [458,'Huyện M\'Đrắk','164'],
    [459,'Huyện Krông Bông','164'],
    [460,'Huyện Krông Pắc','164'],
    [461,'Huyện Krông A Na','164'],
    [462,'Huyện Lắk','164'],
    [463,'Huyện Đắk Glong','165'],
    [464,'Huyện Cư Jút','165'],
    [465,'Huyện Đắk Mil','165'],
    [466,'Huyện Krông Nô','165'],
    [467,'Huyện Đắk Song','165'],
    [468,'Huyện Đắk R\'Lấp','165'],
    [469,'Thị xã Gia Nghĩa','165'],
    [470,'Thành phố Đà Lạt','166'],
    [471,'Thành phố Bảo Lộc','166'],
    [472,'Huyện Lạc Dương','166'],
    [473,'Huyện Lâm Hà','166'],
    [474,'Huyện Đơn Dương','166'],
    [475,'Huyện Đức Trọng','166'],
    [476,'Huyện Di Linh','166'],
    [477,'Huyện Đạ Huoai','166'],
    [478,'Huyện Đạ Tẻh','166'],
    [479,'Huyện Cát Tiên','166'],
    [480,'Huyện Đam Rông','166'],
    [481,'Thị xã Đồng Xoài','167'],
    [482,'Huyện Bù Gia Mập','167'],
    [483,'Huyện Lộc Ninh','167'],
    [484,'Huyện Bù Đốp','167'],
    [485,'Huyện Hớn Quản','167'],
    [486,'Huyện Đồng Phú','167'],
    [487,'Huyện Bù Đăng','167'],
    [488,'Huyện Chơn Thành','167'],
    [489,'Thị xã Tây Ninh','168'],
    [490,'Huyện Tân Biên','168'],
    [491,'Huyện Tân Châu','168'],
    [492,'Huyện Dương Minh Châu','168'],
    [493,'Huyện Châu Thành','168'],
    [494,'Huyện Hòa Thành','168'],
    [495,'Huyện Gò Dầu','168'],
    [496,'Huyện Bến Cầu','168'],
    [497,'Huyện Trảng Bàng','168'],
    [498,'Thành phố Thủ Dầu Một','169'],
    [499,'Huyện Dầu Tiếng','169'],
    [500,'Thị xã Bến Cát','169'],
    [501,'Huyện Phú Giáo','169'],
    [502,'Thị xã Tân Uyên','169'],
    [503,'Thị xã Dĩ An','169'],
    [504,'Thị xã Thuận An','169'],
    [505,'Thành phố Biên Hòa','170'],
    [506,'Thị xã Long Khánh','170'],
    [507,'Huyện Tân Phú','170'],
    [508,'Huyện Vĩnh Cửu','170'],
    [509,'Huyện Định Quán','170'],
    [510,'Huyện Trảng Bom','170'],
    [511,'Huyện Thống Nhất','170'],
    [512,'Huyện Cẩm Mỹ','170'],
    [513,'Huyện Long Thành','170'],
    [514,'Huyện Xuân Lộc','170'],
    [515,'Huyện Nhơn Trạch','170'],
    [516,'Thành phố Vũng Tàu','171'],
    [517,'Thị xã Bà Rịa','171'],
    [518,'Huyện Châu Đức','171'],
    [519,'Huyện Xuyên Mộc','171'],
    [520,'Huyện Long Điền','171'],
    [521,'Huyện Đất Đỏ','171'],
    [522,'Huyện Tân Thành','171'],
    [523,'Huyện Côn Đảo','171'],
    [524,'Quận 1','172',1],
    [525,'Quận 12','172'],
    [526,'Quận Thủ Đức','172'],
    [527,'Quận 9','172'],
    [528,'Quận Gò Vấp','172',1],
    [529,'Quận Bình Thạnh','172',1],
    [530,'Quận Tân Bình','172',1],
    [531,'Quận Tân Phú','172',1],
    [532,'Quận Phú Nhuận','172',1],
    [533,'Quận 2','172',1],
    [534,'Quận 3','172',1],
    [535,'Quận 10','172',1],
    [536,'Quận 11','172',1],
    [537,'Quận 4','172',1],
    [538,'Quận 5','172',1],
    [539,'Quận 6','172',1],
    [540,'Quận 8','172',1],
    [541,'Quận Bình Tân','172'],
    [542,'Quận 7','172',1],
    [543,'Huyện Củ Chi','172'],
    [544,'Huyện Hóc Môn','172'],
    [545,'Huyện Bình Chánh','172'],
    [546,'Huyện Nhà Bè','172'],
    [547,'Huyện Cần Giờ','172'],
    [548,'Thành phố Tân An','173'],
    [549,'Huyện Tân Hưng','173'],
    [550,'Huyện Vĩnh Hưng','173'],
    [551,'Huyện Mộc Hóa','173'],
    [552,'Huyện Tân Thạnh','173'],
    [553,'Huyện Thạnh Hóa','173'],
    [554,'Huyện Đức Huệ','173'],
    [555,'Huyện Đức Hòa','173'],
    [556,'Huyện Bến Lức','173'],
    [557,'Huyện Thủ Thừa','173'],
    [558,'Huyện Tân Trụ','173'],
    [559,'Huyện Cần Đước','173'],
    [560,'Huyện Cần Giuộc','173'],
    [561,'Thành phố Mỹ Tho','174'],
    [562,'Thị xã Gò Công','174'],
    [563,'Huyện Tân Phước','174'],
    [564,'Huyện Cái Bè','174'],
    [565,'Huyện Cai Lậy','174'],
    [566,'Huyện Chợ Gạo','174'],
    [567,'Huyện Gò Công Tây','174'],
    [568,'Huyện Gò Công Đông','174'],
    [569,'Thành phố Bến Tre','175'],
    [570,'Huyện Chợ Lách','175'],
    [571,'Huyện Mỏ Cày Nam','175'],
    [572,'Huyện Giồng Trôm','175'],
    [573,'Huyện Bình Đại','175'],
    [574,'Huyện Ba Tri','175'],
    [575,'Huyện Thạnh Phú','175'],
    [576,'Thành phố Trà Vinh','176'],
    [577,'Huyện Càng Long','176'],
    [578,'Huyện Cầu Kè','176'],
    [579,'Huyện Tiểu Cần','176'],
    [580,'Huyện Cầu Ngang','176'],
    [581,'Huyện Trà Cú','176'],
    [582,'Huyện Duyên Hải','176'],
    [583,'Thành phố Vĩnh Long','177'],
    [584,'Huyện Long Hồ','177'],
    [585,'Huyện Mang Thít','177'],
    [586,'Huyện Vũng Liêm','177'],
    [587,'Huyện Tam Bình','177'],
    [588,'Thị xã Bình Minh','177'],
    [589,'Huyện Trà Ôn','177'],
    [590,'Thành phố Cao Lãnh','178'],
    [591,'Thành phố Sa Đéc','178'],
    [592,'Huyện Tân Hồng','178'],
    [593,'Huyện Hồng Ngự','178'],
    [594,'Huyện Tháp Mười','178'],
    [595,'Huyện Cao Lãnh','178'],
    [596,'Huyện Thanh Bình','178'],
    [597,'Huyện Lấp Vò','178'],
    [598,'Huyện Lai Vung','178'],
    [599,'Thành phố Long Xuyên','179'],
    [600,'Thành phố Châu Đốc','179'],
    [601,'Huyện An Phú','179'],
    [602,'Thị xã Tân Châu','179'],
    [603,'Huyện Phú Tân','179'],
    [604,'Huyện Châu Phú','179'],
    [605,'Huyện Tịnh Biên','179'],
    [606,'Huyện Tri Tôn','179'],
    [607,'Huyện Thoại Sơn','179'],
    [608,'Thành phố Rạch Giá','180'],
    [609,'Thị xã Hà Tiên','180'],
    [610,'Huyện Kiên Lương','180'],
    [611,'Huyện Hòn Đất','180'],
    [612,'Huyện Tân Hiệp','180'],
    [613,'Huyện Giồng Riềng','180'],
    [614,'Huyện Gò Quao','180'],
    [615,'Huyện An Biên','180'],
    [616,'Huyện An Minh','180'],
    [617,'Huyện Vĩnh Thuận','180'],
    [618,'Huyện Phú Quốc','180'],
    [619,'Huyện Kiên Hải','180'],
    [620,'Quận Ninh Kiều','181'],
    [621,'Quận Ô Môn','181'],
    [622,'Quận Bình Thuỷ','181'],
    [623,'Quận Cái Răng','181'],
    [624,'Quận Thốt Nốt','181'],
    [625,'Huyện Cờ Đỏ','181'],
    [626,'Thành phố Vị Thanh','182'],
    [627,'Huyện Châu Thành A','182'],
    [628,'Huyện Phụng Hiệp','182'],
    [629,'Huyện Vị Thuỷ','182'],
    [630,'Huyện Long Mỹ','182'],
    [631,'Thị Xã Ngã Bảy','182'],
    [632,'Thành phố Sóc Trăng','183'],
    [633,'Huyện Kế Sách','183'],
    [634,'Huyện Mỹ Tú','183'],
    [635,'Huyện Cù Lao Dung','183'],
    [636,'Huyện Long Phú','183'],
    [637,'Huyện Mỹ Xuyên','183'],
    [638,'Thị xã Ngã Năm','183'],
    [639,'Huyện Thạnh Trị','183'],
    [640,'Thị xã Vĩnh Châu','183'],
    [641,'Thành phố Bạc Liêu','184'],
    [642,'Huyện Hồng Dân','184'],
    [643,'Huyện Phước Long','184'],
    [644,'Huyện Vĩnh Lợi','184'],
    [645,'Huyện Giá Rai','184'],
    [646,'Huyện Đông Hải','184'],
    [647,'Huyện Hòa Bình','184'],
    [648,'Thành phố Cà Mau','185'],
    [649,'Huyện U Minh','185'],
    [650,'Huyện Thới Bình','185'],
    [651,'Huyện Trần Văn Thời','185'],
    [652,'Huyện Cái Nước','185'],
    [653,'Huyện Đầm Dơi','185'],
    [654,'Huyện Năm Căn','185'],
    [655,'Huyện Ngọc Hiển','185'],
    [656,'Huyện Mường ảng','129'],
    [657,'Huyện Tuy Đức','165'],
    [658,'Huyện Tân Sơn','138'],
    [659,'Huyện U Minh Thượng','180'],
    [660,'Huyện Phú Thiện','163'],
    [661,'Huyện Lộc Hà','150'],
    [662,'Huyện Cam Lâm','159'],
    [663,'Huyện Cư Kuin','164'],
    [664,'Quận Dương Kinh','142'],
    [665,'Huyện Bình Tân','177'],
    [666,'Tân Phú Đông','174'],
    [667,'Huyện Nông Sơn','155'],
    [668,'Thị xã Thái Hoà','149'],
    [669,'Huyện Tân Uyên','130'],
    [670,'Huyện Thới Lai','181'],
    [671,'Thị xã Buôn Hồ','164'],
    [672,'Huyện Mỏ Cày Bắc','175'],
    [673,'Huyện Sông Lô','139'],
    [674,'Thị xã Hồng Ngự','178'],
    [675,'Huyện Giang Thành','180'],
    [676,'Huyện Thuận Nam','160'],
    [677,'Thị xã Bình Long','167'],
    [678,'Thị xã Phước Long','167'],
    [679,'Huyện Chư Pưh','163'],
    [680,'Huyện Trần Đề','183'],
    [681,'Huyện Lâm Bình','127'],
    [682,'Thị xã Kiến Tường','173'],
    [683,'Huyện Nậm Pồ','129'],
    [684,'Huyện Nậm Nhùn','130'],
    [685,'Thị xã Hoàng Mai','149'],
    [686,'Huyện Vân Hồ','131'],
    [687,'Huyện Bàu Bàng','169'],
    [688,'Huyện Bắc Tân Uyên','169'],
    [689,'Quận Bắc Từ Liêm','123'],
    [690,'Thị xã Cai Lậy','174'],
    [691,'Thị xã Ba Đồn','151'],
    [692,'Huyện Ia H\'Drai','162'],
    [693,'Thị xã Duyên Hải','176'],
    [694,'Huyện Phú Riềng','167'],
    [695,'Thị xã Long Mỹ','182'],
    [696,'Thị xã Kỳ Anh','150'],
    [697,'Huyện Bảo Lâm','166'],
    [698,'Huyện Châu Thành','179'],
    [699,'Huyện Châu Thành','175'],
    [700,'Huyện Phú Tân','185'],
    [701,'Huyện Vĩnh Thạnh','181'],
    [702,'Huyện Phong Điền','181'],
    [703,'Huyện Châu Thành','178'],
    [704,'Huyện Tam Nông','178'],
    [705,'Quận Ba Đình','123'],
    [706,'Huyện Châu Thành','182'],
    [707,'Huyện Châu Thành','180'],
    [708,'Huyện Châu Thành','173'],
    [709,'Huyện Kỳ Sơn','149'],
    [710,'Huyện Châu Thành','183'],
    [711,'Huyện Châu Thành','174'],
    [712,'Huyện Châu Thành','176']
  ];

  try {
    foreach ($arrRole as $role) {
      Capsule::insert('INSERT INTO ' . Capsule::getTablePrefix()
        . 'role (id, title, created_at, updated_at)'
        . 'VALUES (?, ?, ?, ?)',
        $role
      );
    }

    foreach ($arrPermission as $key => $permission) {
      array_unshift($permission, $key + 1);
      Capsule::insert('INSERT INTO ' . Capsule::getTablePrefix()
        . 'permission (id, role_id, `group`, method, endpoint, created_at, updated_at)'
        . 'VALUES (?, ?, ?, ?, ?, ?, ?)',
        $permission
      );
    }

    foreach ($arrRegion as $region){
      Capsule::insert('INSERT INTO ' . Capsule::getTablePrefix()
        . 'region (id, `name`, region_code)'
        . 'VALUES (?, ?, ?)',
        $region
      );
    }

    foreach ($arrSubRegion as $subRegion){
      Capsule::insert('INSERT INTO ' . Capsule::getTablePrefix()
        . 'subregion (id, `name`, region_id)'
        . 'VALUES (?, ?, ?)',
        $subRegion
      );
    }

    if (!file_exists(ROOT . '/public/uploads')) {
      mkdir(ROOT . '/public/uploads', 0755, true);
    }

    if (!file_exists(ROOT . '/public/uploads/origin')) {
      mkdir(ROOT . '/public/uploads/origin', 0755, true);
    }

    if (!file_exists(ROOT . '/public/themes')) {
      mkdir(ROOT . '/public/themes', 0755, true);
    }

    if (!file_exists(ROOT . '/public/images')) {
      mkdir(ROOT . '/public/images', 0755, true);
    }
  } catch (Exception $e) {

  }
